### ISSUE TITLE
Choice of the initial tab

### ISSUE THREAD

**Issue by eg9** [TeX-Live/tlcockpit#17]
When TLCockpit starts up, it always opens with the “Packages” tab.

This is different from TeX Live Utility that starts up with the “Updates” tab, which I find more useful, because people mostly use these utilities for updating their distribution. The list of available updates should be shown without the need of asking for it (which already happens when one switches to the “Updates” tab).

Therefore I suggest to make this the default. Another reason I find important is that loading the list of packages takes much longer than the list of updates.

**Comment by norbusan** [comment]
Ciao Enrico,

ok, I will see if I can do this as an option or some other way. But be reminded that the loading of the packages will happen *anyway* since we need to load the local and remote database to compare the versions ;-)

**Comment by norbusan** [comment]
Hi Enrico,

took me a bit of time ;-) Fixed in https://github.com/TeX-Live/tlcockpit/commit/f9a38358843c3437dd943367f5971cfaab8ef6d7 and will be in the next release.
