### ISSUE TITLE
tlcockpit seems to run into an infinite loop on exit

### ISSUE THREAD

**Issue by 7Z0t99** [TeX-Live/tlcockpit#2]
I have tried tlcockpit from TeX Live rev 45426 running on Win 7 64 bit with the 64bit Oracle jre 8u141. It really feels a lot more fluid than tlmgr-gui!
When I close tlcockpit, its window closes but in the background its javaw.exe seems to run into an infinite loop.

**Comment by norbusan** [comment]
Can you try to run it from a cmd window manually with `java -jar ...../tlcockpit.jar` and see if the same happens?

**Comment by 7Z0t99** [comment]
I just tried: the same happens.

**Comment by norbusan** [comment]
Hmm, thanks. Needs investigation (but rarely I use Win7 and on Win10 it works).

**Comment by abenori** [comment]
I have the same problem with Win 10.

**Comment by norbusan** [comment]
Hmmm, do you have texlive.infra from tlcritical installed?

**Comment by abenori** [comment]
No, I only use tlnet.

**Comment by norbusan** [comment]
Hmm, that should actually be enough. What version of Java are you running? On my Windows10 I don't see this behaviour.

**Comment by abenori** [comment]
The result of `java -showversion` is: 
```
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) Client VM (build 25.141-b15, mixed mode)
```

**Comment by norbusan** [comment]
Hmm, all my systems have _144 installed. Could you try out some 1.8 144 version and see if this changes anything?

**Comment by abenori** [comment]
I updated it to _151 and had the same problem. I'll look for _144.

**Comment by norbusan** [comment]
No, there should be no need to test that.
Thanks for testing 151, that is enough.

**Comment by norbusan** [comment]
This is really strange. I have now done the following:

- removed all Java installations I have
- installed java 1.8 152:
```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```
- update my TeX Live installation on Win10, other than tlnet nothing activated
- started tlcockpit
- played around, exit

and there was no hang whatsoever ...

**Comment by norbusan** [comment]
Ahhh, I see now what happens:
When you close tlcockpit with the X of the window manager, it hangs.
When you close tlcockpit with the menu entry TLCockpit -> Exit it does not hang

Can you confirm this?

**Comment by 7Z0t99** [comment]
Yes, I can. To be honest I hadn't thought of closing the program via the menu entry before I read your post; I always used the X

**Comment by norbusan** [comment]
It is supposed to do the same, I have added a special exit function and on Linux it does work, but somehow the way how Windows terminates programs via the X seems to be different. I need to investigate ...

**Comment by abenori** [comment]
> Yes, I can. 

Me too!

**Comment by norbusan** [comment]
Thanks for checking!

**Comment by norbusan** [comment]
Can you two please try with the new jar pulled from master branch here? I have added additional shutdown code and now it works at least on my win10 when using the Exit menu item (as before) but also when closing the Window with the X button.

Thanks

**Comment by abenori** [comment]
looks good!

**Comment by norbusan** [comment]
Thanks for testing. I will *not* push an update to TL, though, because I first want to get the JSON functionality in shape (texlive.infra/tlmgr side) and make tlcockpit use the json output, allowing for more detailed display.

Anyway, I am closing this since it is fixed in the code.

Thanks

Norbert
