### ISSUE TITLE
tlive cockpit don't show package to be update

### ISSUE THREAD

**Issue by maieul** [TeX-Live/tlcockpit#5]
With TeXLive2017 Vanilla on Ubuntu 16.04

Here is what texlive show me as package to be updated
![capture d ecran_2017-11-25_09-31-57](https://user-images.githubusercontent.com/636640/33228829-f46e34e4-d1c3-11e7-905e-0e4513867ee0.png)

But a tlmgr update --all update me 97 packages.

**Comment by norbusan** [comment]
Interesting, can you show me the output of `tlmgr -v version`?

**Comment by maieul** [comment]
tlmgr revision 45838 (2017-11-17 03:13:42 +0100)
tlmgr using installation: /usr/local/texlive/2017
TeX Live (http://tug.org/texlive) version 2017

**Comment by norbusan** [comment]
Hmm, interesting, so that is the newest. Can you send me the java version: `java -version` and before updating the output of `tlmgr update --list --machine-readable`?

**Comment by maieul** [comment]
Strange, I tested today, and it works. I think we can close.
