### ISSUE TITLE
Cut/copy from information

### ISSUE THREAD

**Issue by ghoetker** [TeX-Live/tlcockpit#8]
Would it be possible to make the information in the Information window copyable?  I capture that information from tlmgr to make my own cheat sheet of packages that might be useful in the future. Thanks.

**Comment by norbusan** [comment]
Hmm, that is a restriction in JavaFX/ScalaFX, see https://bugs.openjdk.java.net/browse/JDK-8091644
I might try to work around that by not using labels but textfields, but it is a major rework of the information window structure, so I'm not sure when I have the time.

**Comment by norbusan** [comment]
I did what I can do, please grab the latest .jar file from github and try it out. All texts are now copyable one by one (but not all in one go). The only exception are files listed in a listbox with scrollbar, there I don't have any idea how to make that selectable.

Hope that helps.
